Enable/disable hash and serialize for AnyWrapper
All thanks to David's (@wavefunction91) kind help.

There is still a compiler error that needs to be fixed:
```
In file included from /home/keceli/soft/nwx/pp_any_refactor/include/pluginplay/detail_/any.hpp:2,
                 from /home/keceli/soft/nwx/pp_any_refactor/include/pluginplay/cache/cache.hpp:2,
                 from /home/keceli/soft/nwx/pp_any_refactor/tests/pluginplay/cache/cache.cpp:1:
/home/keceli/soft/nwx/pp_any_refactor/include/pluginplay/detail_/any_wrapper.hpp: In instantiation of 'std::enable_if_t<is_output_type_v<AnyTag> > pluginplay::detail_::AnyWrapper<T, AnyTag>::serialize_(pluginplay::detail_::Serializer&) const [with T = std::vector<int>; AnyTag = pluginplay::detail_::AnyGeneral; std::enable_if_t<is_output_type_v<AnyTag> > = void; pluginplay::detail_::Serializer = pluginplay::detail_::ArchiveWrapper<std::variant<madness::archive::CerealOutputArchive<cereal::BinaryOutputArchive>*, madness::archive::CerealOutputArchive<cereal::PortableBinaryOutputArchive>*, madness::archive::CerealOutputArchive<cereal::JSONOutputArchive>*, madness::archive::CerealOutputArchive<cereal::XMLOutputArchive>*> >]':
/home/keceli/soft/nwx/pp_any_refactor/include/pluginplay/detail_/any_wrapper.hpp:539:48:   required from here
/home/keceli/soft/nwx/pp_any_refactor/include/pluginplay/detail_/any_wrapper.hpp:550:17: error: 'std::map<long unsigned int, std::function<std::unique_ptr<pluginplay::detail_::AnyWrapperBase<>, std::default_delete<pluginplay::detail_::AnyWrapperBase<> > >(pluginplay::detail_::ArchiveWrapper<std::variant<madness::archive::CerealInputArchive<cereal::BinaryInputArchive>*, madness::archive::CerealInputArchive<cereal::PortableBinaryInputArchive>*, madness::archive::CerealInputArchive<cereal::JSONInputArchive>*, madness::archive::CerealInputArchive<cereal::XMLInputArchive>*> >&)>, std::less<long unsigned int>, std::allocator<std::pair<const long unsigned int, std::function<std::unique_ptr<pluginplay::detail_::AnyWrapperBase<>, std::default_delete<pluginplay::detail_::AnyWrapperBase<> > >(pluginplay::detail_::ArchiveWrapper<std::variant<madness::archive::CerealInputArchive<cereal::BinaryInputArchive>*, madness::archive::CerealInputArchive<cereal::PortableBinaryInputArchive>*, madness::archive::CerealInputArchive<cereal::JSONInputArchive>*, madness::archive::CerealInputArchive<cereal::XMLInputArchive>*> >&)> > > > pluginplay::detail_::AnyWrapperBase<>::m_any_maker_' is private within this context
  550 |             if(!base_type::m_any_maker_->count(idx)) {
      |                 ^~~~~~~~~
```
[skip ci]