Enable caching (#138)
* Add missing header

Without <sdeexcept> build fails with:
```
/Users/keceli/tmp/nwx/mySDE/sde/field_tuple.hpp:234:20: error: 'invalid_argument' is not a member of 'std'
```

* Enable caching

Just remove the booleans that disables caching.
Caching reduces the runtime of NWChemEx test
by more than 6 times.

* Added reset_cache function

* Reset cache with change_submod

When submodules are changed within a calculation,
old result from the cache migth be used: i.e. sde
lambda_module example test was failing for this reason.
Here we reset the cache whenever one changes
a submodule as a precaution.

* Add funcs to turn on/off memoization for modules

Some modules should not be memoized such as the ones
with nondeterministic results.

* Turn off memoization for lambda_module

* fix typo

* Added tests for memoization functions

* Add a warning for using reset_cache

* Add reset_cache to module API

* Added an example test for reset_cache

* Use @warning

* Use public API

* Check submodules for is_memoizable

No need to change memoizability within change_submod

* Add unit tests for submodules memoizability

* clang-format

* Added more unit tests

* More coverage for module_pimpl

* Add a warning to memoization funcs for modules without a cache

* Added unit tests for modules with or without a cache

* Removed unnecessary unit tests

* Update get_dependencies.sh

Trying to fix the CI build that fails with:

```
Getting dependency: gcovr
Collecting gcovr
  Downloading gcovr-4.2-py2.py3-none-any.whl (45 kB)
Collecting jinja2
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting lxml
  Downloading lxml-4.5.2.tar.gz (4.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zc6b_fqp/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zc6b_fqp/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ums1exl4
         cwd: /tmp/pip-install-zc6b_fqp/lxml/
    Complete output (3 lines):
    Building lxml version 4.5.2.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: Process completed with exit code 1.
```

* Update get_dependencies.sh