Add missing header
Without <sdeexcept> build fails with:
```
/Users/keceli/tmp/nwx/mySDE/sde/field_tuple.hpp:234:20: error: 'invalid_argument' is not a member of 'std'
```